name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate changelog
      id: changelog
      run: |
        # Get the previous tag
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        
        # Generate changelog
        if [ -n "$PREV_TAG" ]; then
          CHANGELOG=$(git log --pretty=format:"- %s" $PREV_TAG..HEAD | grep -v "Merge pull request")
        else
          CHANGELOG=$(git log --pretty=format:"- %s" | grep -v "Merge pull request")
        fi
        
        # Save changelog to file
        echo "$CHANGELOG" > CHANGELOG.txt
        
        # Set output for use in release
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## Changes in this Release
          
          ${{ steps.changelog.outputs.changelog }}
          
          ## Installation
          
          ```bash
          docker extension install telkombe/remote-docker:${{ github.ref_name }}
          ```
          
          ## Docker Hub
          
          - **Image**: `telkombe/remote-docker:${{ github.ref_name }}`
          - **Latest**: `telkombe/remote-docker:latest`
          
          ## Documentation
          
          See the [README](https://github.com/anubissbe/remote-docker/blob/main/README.md) for installation and usage instructions.
        draft: false
        prerelease: false

  notify-docker-hub:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
    - name: Notify Docker Hub webhook
      if: success()
      run: |
        echo "Release ${{ github.ref_name }} created successfully"
        echo "Docker image should be available at telkombe/remote-docker:${{ github.ref_name }}"