# Funding configuration for Remote Docker Extension

# GitHub Sponsors
github: [telkombe]

# Other funding platforms
# patreon: username
# open_collective: username
# ko_fi: username
# liberapay: username
# issuehunt: username
# otechie: username
# custom: ['https://example.com']