# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - ui
    - mcp-servers
    - scripts
    - docs
    - tests

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - prealloc
    - predeclared
    - asciicheck
    - errorlint
    - exhaustivestruct
    - exportloopref
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - goerr113
    - nestif
    - revive
    - testpackage
    - wsl

  disable:
    - interfacer # deprecated
    - maligned   # deprecated
    - scopelint  # deprecated

linters-settings:
  depguard:
    list-type: blacklist
    packages:
      - github.com/sirupsen/logrus # use standard log/slog instead
    
  dupl:
    threshold: 100
    
  exhaustive:
    default-signifies-exhaustive: false
    
  funlen:
    lines: 100
    statements: 50
    
  gci:
    local-prefixes: github.com/anubissbe/remote-docker
    
  goconst:
    min-len: 2
    min-occurrences: 2
    
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      
  gocyclo:
    min-complexity: 15
    
  goimports:
    local-prefixes: github.com/anubissbe/remote-docker
    
  golint:
    min-confidence: 0
    
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
        
  govet:
    check-shadowing: true
    
  lll:
    line-length: 140
    
  misspell:
    locale: US
    
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
    
  rowserrcheck:
    packages:
      - database/sql

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - dupl
        
    - path: pkg/golinters/errcheck.go
      text: "SA1019: errCfg.Exclude is deprecated: use ExcludeFunctions instead"
      
    - path: pkg/commands/run.go
      text: "SA1019: lsc.Errcheck.Exclude is deprecated: use ExcludeFunctions instead"
      
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false