services:
  remote-docker:
    image: ${DESKTOP_PLUGIN_IMAGE}
    volumes:
      # Mount SSH configuration from the host (user's machine) to a temp location
      - ~/.ssh:/root/.ssh-host:ro
      # Plugin data with better persistence
      - "remote-docker-settings:/root/docker-extension/"

volumes:
  remote-docker-settings: